# Generated by Django 5.2.4 on 2025-07-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_choices',
            field=models.CharField(choices=[('guest', 'guest'), ('host', 'host')], max_length=10),
        ),
    ]
