# Generated by Django 5.2.4 on 2025-07-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_alter_userprofile_role_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
