# Generated by Django 5.2.4 on 2025-07-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_delete_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rules',
            field=models.CharField(choices=[('no_smoking', 'no_smoking'), ('pets_allowed', 'pets_allowed'), ('etc', 'etc')], max_length=12),
        ),
    ]
